//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_CONTINUE2                   154
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     157
#define IDB_BITMAP4                     158
#define IDB_PLAYER0_RUN3_REVERSE        158
#define IDB_BITMAP5                     159
#define IDB_BITMAP6                     160
#define IDB_BITMAP7                     161
#define IDB_BITMAP8                     162
#define IDB_BITMAP9                     163
#define IDB_BITMAP10                    165
#define IDB_BITMAP11                    169
#define IDB_BITMAP12                    170
#define IDB_PLAYER1_NORMAL1             171
#define IDB_PLAYER7                     172
#define IDB_PLAYER1_WALK4               172
#define IDB_PLAYER1_NORMAL2             173
#define IDB_PLAYER1_NORMAL3             174
#define IDB_PLAYER1_NORMAL4             175
#define IDB_PLAYER1_WALK1               176
#define IDB_PLAYER1_WALK2               177
#define IDB_PLAYER1_WALK3               178
#define IDB_PLAYER1_ATTACK1             179
#define IDB_PLAYER1_ATTACK2             180
#define IDB_PLAYER1_ATTACK3             181
#define IDB_PLAYER1_ATTACK4             182
#define IDB_PLAYER1_ATTACK5             183
#define IDB_PLAYER1_ATTACK6             184
#define IDB_BITMAP13                    186
#define BITMAP_PRESSATTACK_0            187
#define PHOTOSTICKER_FIRZEN             188
#define PHOTOSTICKER_FREEZE             189
#define PHOTOSTICKER_HENRY              190
#define IDB_PLAYER1_NORMAL4_REVERSE     191
#define IDB_PLAYER1_NORMAL3_REVERSE     192
#define IDB_PLAYER1_NORMAL2_REVERSE     193
#define IDB_PLAYER1_NORMAL1_REVERSE     194
#define IDB_PLAYER1_WALK4_REVERSE       195
#define IDB_PLAYER1_WALK3_REVERSE       196
#define IDB_PLAYER1_WALK2_REVERSE       197
#define IDB_PLAYER1_WALK1_REVERSE       198
#define IDB_PLAYER1_ATTACK6_REVERSE     199
#define IDB_PLAYER1_ATTACK5_REVERSE     200
#define IDB_PLAYER1_ATTACK4_REVERSE     201
#define IDB_PLAYER1_ATTACK3_REVERSE     202
#define IDB_PLAYER1_ATTACK2_REVERSE     203
#define IDB_PLAYER1_ATTACK1_REVERSE     204
#define IDB_PLAYER1_JUMP1               205
#define IDB_PLAYER1_JUMP2               206
#define IDB_PLAYER1_JUMP3               207
#define IDB_PLAYER1_JUMP3_REVERSE       208
#define IDB_PLAYER1_JUMP2_REVERSE       209
#define IDB_PLAYER1_JUMP1_REVERSE       210
#define IDB_PLAYER1_RUN1                211
#define IDB_PLAYER1_RUN2                212
#define IDB_PLAYER1_RUN3                213
#define IDB_PLAYER1_RUN3_REVERSE        214
#define IDB_PLAYER1_RUN2_REVERSE        215
#define IDB_PLAYER1_RUN1_REVERSE        216
#define IDB_PLAYER0_NORMAL1             217
#define IDB_PLAYER0_NORMAL2             218
#define IDB_PLAYER0_NORMAL3             219
#define IDB_PLAYER0_NORMAL4             220
#define IDB_PLAYER0_WALK1               221
#define IDB_PLAYER0_WALK2               222
#define IDB_PLAYER0_WALK3               223
#define IDB_PLAYER0_WALK4               224
#define IDB_PLAYER0_WALK4_REVERSE       225
#define IDB_PLAYER0_WALK3_REVERSE       226
#define IDB_PLAYER0_WALK2_REVERSE       227
#define IDB_PLAYER0_WALK1_REVERSE       228
#define IDB_PLAYER0_KNOCK1              229
#define IDB_PLAYER0_KNOCK2              230
#define IDB_PLAYER0_KNOCK3              231
#define IDB_PLAYER0_KNOCK4              232
#define IDB_PLAYER0_KNOCK5              233
#define IDB_PLAYER0_GETUP1              234
#define IDB_PLAYER0_GETUP2              235
#define IDB_PLAYER0_GETUP2_REVERSE      237
#define IDB_PLAYER0_GETUP1_REVERSE      238
#define IDB_PLAYER0_KNOCK5_REVERSE      239
#define IDB_PLAYER0_KNOCK4_REVERSE      240
#define IDB_PLAYER0_KNOCK3_REVERSE      241
#define IDB_PLAYER0_KNOCK2_REVERSE      242
#define IDB_PLAYER0_KNOCK1_REVERSE      243
#define IDB_PLAYER0_KNOCKBACK1          244
#define IDB_PLAYER0_KNOCKBACK2          245
#define IDB_PLAYER0_KNOCKBACK3          246
#define IDB_PLAYER0_KNOCKBACK4          247
#define IDB_PLAYER0_KNOCKBACK5          248
#define IDB_PLAYER0_GETUPBACK1          249
#define IDB_PLAYER0_GETUPBACK1_REVERSE  251
#define IDB_PLAYER0_KNOCKBACK5_REVERSE  252
#define IDB_PLAYER0_KNOCKBACK4_REVERSE  253
#define IDB_PLAYER0_KNOCKBACK3_REVERSE  254
#define IDB_PLAYER0_KNOCKBACK2_REVERSE  255
#define IDB_PLAYER0_KNOCKBACK1_REVERSE  256
#define IDB_PLAYER1_GETUP1              257
#define IDB_PLAYER1_GETUP1_REVERSE      258
#define IDB_PLAYER1_GETUP2              259
#define IDB_PLAYER1_GETUP2_REVERSE      260
#define IDB_PLAYER1_KNOCKBACK5_REVERSE  261
#define IDB_PLAYER1_KNOCKBACK5          262
#define IDB_PLAYER1_GETUPBACK1          263
#define IDB_PLAYER1_GETUPBACK1_REVERSE  264
#define IDB_PLAYER1_KNOCK1              265
#define IDB_PLAYER1_KNOCK1_REVERSE      266
#define IDB_PLAYER1_KNOCKBACK4_REVERSE  267
#define IDB_PLAYER1_KNOCK2              268
#define IDB_PLAYER1_KNOCK2_REVERSE      269
#define IDB_PLAYER1_KNOCK3              270
#define IDB_PLAYER1_KNOCK3_REVERSE      271
#define IDB_PLAYER1_KNOCK4              272
#define IDB_PLAYER1_KNOCK4_REVERSE      273
#define IDB_PLAYER1_KNOCK5              274
#define IDB_PLAYER1_KNOCK5_REVERSE      275
#define IDB_PLAYER1_KNOCKBACK1          276
#define IDB_PLAYER1_KNOCKBACK1_REVERSE  277
#define IDB_PLAYER1_KNOCKBACK2          278
#define IDB_PLAYER1_KNOCKBACK2_REVERSE  279
#define IDB_PLAYER1_KNOCKBACK4          280
#define IDB_PLAYER1_KNOCKBACK3          281
#define IDB_PLAYER1_KNOCKBACK3_REVERSE  282
#define BITMAP_COUNTDOWN_1              283
#define BITMAP_COUNTDOWN_2              284
#define BITMAP_COUNTDOWN_3              285
#define BITMAP_COUNTDOWN_4              286
#define BITMAP_COUNTDOWN_5              287
#define BITMAP_PRESSATTACK_1            288
#define BITMAP_BLACKSCREEN              289
#define BITMAP_NUMBER_1                 290
#define BITMAP_NUMBER_0                 291
#define IDB_PLAYER0_NORMAL4_REVERSE     292
#define BITMAP_FOREST_M1                293
#define IDB_BITMAP28                    294
#define BITMAP_NUMBER_2                 295
#define IDB_BITMAP29                    296
#define BITMAP_NUMBER_3                 297
#define IDB_BITMAP30                    298
#define NAME_FIRZEN                     299
#define IDB_BITMAP31                    300
#define NAME_FREEZE                     301
#define IDB_BITMAP32                    302
#define NAME_HENRY                      303
#define IDB_PLAYER0_NORMAL3_REVERSE     304
#define IDB_PLAYER0_NORMAL2_REVERSE     305
#define IDB_PLAYER0_NORMAL1_REVERSE     306
#define IDB_PLAYER0_ATTACK1             307
#define IDB_PLAYER0_ATTACK2             308
#define IDB_PLAYER0_ATTACK3             309
#define IDB_PLAYER0_ATTACK4             310
#define IDB_PLAYER0_ATTACK5             311
#define IDB_PLAYER0_ATTACK6             312
#define IDB_PLAYER0_ATTACK7             313
#define IDB_PLAYER0_ATTACK8             314
#define IDB_PLAYER0_ATTACK8_REVERSE     315
#define IDB_PLAYER0_ATTACK7_REVERSE     316
#define IDB_PLAYER0_ATTACK6_REVERSE     317
#define IDB_PLAYER0_ATTACK5_REVERSE     318
#define IDB_PLAYER0_ATTACK4_REVERSE     319
#define IDB_PLAYER0_ATTACK3_REVERSE     320
#define IDB_PLAYER0_ATTACK2_REVERSE     321
#define IDB_PLAYER0_ATTACK1_REVERSE     322
#define IDB_PLAYER0_JUMP1               323
#define IDB_PLAYER0_JUMP2               324
#define IDB_PLAYER0_JUMP3               325
#define IDB_PLAYER0_JUMP3_REVERSE       326
#define IDB_PLAYER0_JUMP2_REVERSE       327
#define IDB_PLAYER0_JUMP1_REVERSE       328
#define IDB_PLAYER0_RUN1                329
#define IDB_PLAYER0_RUN2                330
#define IDB_PLAYER0_RUN3                331
#define IDB_PLAYER0_RUN1_REVERSE        332
#define IDB_PLAYER0_RUN2_REVERSE        333
#define FIRZEN_NORMAL1                  334
#define FIRZEN_NORMAL2                  335
#define FIRZEN_NORMAL3                  336
#define FIRZEN_NORMAL4                  337
#define FIRZEN_NORMAL4_REVERSE          338
#define FIRZEN_NORMAL3_REVERSE          339
#define FIRZEN_NORMAL2_REVERSE          340
#define FIRZEN_NORMAL1_REVERSE          341
#define FIRZEN_WALK1                    342
#define FIRZEN_WALK2                    343
#define FIRZEN_WALK3                    344
#define FIRZEN_WALK4                    345
#define FIRZEN_WALK4_REVERSE            346
#define FIRZEN_WALK3_REVERSE            347
#define FIRZEN_WALK2_REVERSE            348
#define FIRZEN_WALK1_REVERSE            349
#define FIRZEN_ATTACK1                  350
#define FIRZEN_ATTACK2                  351
#define FIRZEN_ATTACK3                  352
#define FIRZEN_ATTACK4                  353
#define FIRZEN_ATTACK5                  354
#define FIRZEN_ATTACK6                  355
#define FIRZEN_ATTACK7                  356
#define FIRZEN_JUMP1                    357
#define FIRZEN_JUMP2                    358
#define FIRZEN_JUMP3                    359
#define FIRZEN_JUMP3_REVERSE            360
#define FIRZEN_JUMP2_REVERSE            361
#define FIRZEN_JUMP1_REVERSE            362
#define FIRZEN_ATTACK7_REVERSE          363
#define FIRZEN_ATTACK6_REVERSE          364
#define FIRZEN_ATTACK5_REVERSE          365
#define FIRZEN_ATTACK4_REVERSE          366
#define FIRZEN_ATTACK3_REVERSE          367
#define FIRZEN_ATTACK2_REVERSE          368
#define FIRZEN_ATTACK1_REVERSE          369
#define FIRZEN_RUN1                     370
#define FIRZEN_RUN2                     371
#define FIRZEN_RUN3                     372
#define FIRZEN_RUN3_REVERSE             373
#define FIRZEN_RUN2_REVERSE             374
#define FIRZEN_RUN1_REVERSE             375
#define FIRZEN_KNOCK1                   376
#define FIRZEN_KNOCK2                   377
#define FIRZEN_KNOCK3                   378
#define FIRZEN_KNOCK4                   379
#define FIRZEN_KNOCK5                   380
#define FIRZEN_KNOCK5_REVERSE           381
#define FIRZEN_KNOCK4_REVERSE           382
#define FIRZEN_KNOCK3_REVERSE           383
#define FIRZEN_KNOCK2_REVERSE           384
#define FIRZEN_KNOCK1_REVERSE           385
#define FIRZEN_KNOCKBACK1               386
#define FIRZEN_KNOCKBACK2               387
#define FIRZEN_KNOCKBACK3               388
#define FIRZEN_KNOCKBACK4               389
#define FIRZEN_KNOCKBACK5               390
#define FIRZEN_KNOCKBACK5_REVERSE       391
#define FIRZEN_KNOCKBACK4_REVERSE       392
#define FIRZEN_KNOCKBACK3_REVERSE       393
#define FIRZEN_KNOCKBACK2_REVERSE       394
#define FIRZEN_KNOCKBACK1_REVERSE       395
#define FIRZEN_GETUP1                   396
#define FIRZEN_GETUP2                   397
#define FIRZEN_GETUP2_REVERSE           398
#define FIRZEN_GETUP1_REVERSE           399
#define FIRZEN_GETUPBACK1               400
#define FIRZEN_GETUPBACK1_REVERSE       401
#define FREEZE_NORMAL1                  402
#define FREEZE_NORMAL2                  403
#define FREEZE_NORMAL3                  404
#define FREEZE_NORMAL4                  405
#define FREEZE_NORMAL4_REVERSE          406
#define FREEZE_NORMAL3_REVERSE          407
#define FREEZE_NORMAL2_REVERSE          408
#define FREEZE_NORMAL1_REVERSE          409
#define FREEZE_WALK1                    410
#define FREEZE_WALK2                    411
#define FREEZE_WALK3                    412
#define FREEZE_WALK4                    413
#define FREEZE_WALK4_REVERSE            414
#define FREEZE_WALK3_REVERSE            415
#define FREEZE_WALK2_REVERSE            416
#define FREEZE_WALK1_REVERSE            417
#define FREEZE_ATTACK1                  418
#define FREEZE_ATTACK2                  419
#define FREEZE_ATTACK3                  420
#define FREEZE_ATTACK4                  421
#define FREEZE_ATTACK5                  422
#define FREEZE_ATTACK6                  423
#define FREEZE_ATTACK7                  424
#define FREEZE_ATTACK8                  425
#define FREEZE_ATTACK9                  426
#define FREEZE_ATTACK10                 427
#define IDB_BITMAP41                    428
#define BITMAP_HEALTHBAR                428
#define FREEZE_ATTACK10_REVERSE         429
#define FREEZE_ATTACK9_REVERSE          430
#define FREEZE_ATTACK8_REVERSE          431
#define FREEZE_ATTACK7_REVERSE          432
#define FREEZE_ATTACK6_REVERSE          433
#define FREEZE_ATTACK5_REVERSE          434
#define FREEZE_ATTACK4_REVERSE          435
#define FREEZE_ATTACK3_REVERSE          436
#define FREEZE_ATTACK2_REVERSE          437
#define FREEZE_ATTACK1_REVERSE          438
#define FREEZE_JUMP1                    439
#define FREEZE_JUMP2                    440
#define FREEZE_JUMP3                    441
#define FREEZE_JUMP3_REVERSE            442
#define FREEZE_JUMP2_REVERSE            443
#define FREEZE_JUMP1_REVERSE            444
#define FREEZE_RUN1                     445
#define FREEZE_RUN2                     446
#define FREEZE_RUN3                     447
#define FREEZE_RUN3_REVERSE             448
#define FREEZE_RUN2_REVERSE             449
#define FREEZE_RUN1_REVERSE             450
#define IDB_BITMAP42                    451
#define IDB_CONTINU                     451
#define FREEZE_KNOCK1                   452
#define FREEZE_KNOCK2                   453
#define FREEZE_KNOCK3                   454
#define FREEZE_KNOCK4                   455
#define FREEZE_KNOCK5                   456
#define FREEZE_KNOCK5_REVERSE           457
#define FREEZE_KNOCK4_REVERSE           458
#define FREEZE_KNOCK3_REVERSE           459
#define FREEZE_KNOCK2_REVERSE           460
#define FREEZE_KNOCK1_REVERSE           461
#define FREEZE_KNOCKBACK1               462
#define FREEZE_KNOCKBACK2               463
#define FREEZE_KNOCKBACK3               464
#define FREEZE_KNOCKBACK4               465
#define FREEZE_KNOCKBACK5               466
#define FREEZE_KNOCKBACK1_REVERSE       467
#define FREEZE_KNOCKBACK2_REVERSE       468
#define FREEZE_KNOCKBACK3_REVERSE       469
#define FREEZE_KNOCKBACK4_REVERSE       470
#define FREEZE_KNOCKBACK5_REVERSE       471
#define FREEZE_GETUP1                   472
#define FREEZE_GETUP2                   473
#define FREEZE_GETUP2_REVERSE           474
#define FREEZE_GETUP1_REVERSE           475
#define FREEZE_GETUPBACK1               476
#define FREEZE_GETUPBACK1_REVERSE       477
#define HENRY_NORMAL1                   478
#define HENRY_NORMAL2                   479
#define HENRY_NORMAL3                   480
#define HENRY_NORMAL4                   481
#define HENRY_NORMAL4_REVERSE           482
#define HENRY_NORMAL3_REVERSE           483
#define HENRY_NORMAL2_REVERSE           484
#define HENRY_NORMAL1_REVERSE           485
#define HENRY_WALK1                     486
#define HENRY_WALK2                     487
#define HENRY_WALK3                     488
#define HENRY_WALK4                     489
#define HENRY_WALK4_REVERSE             491
#define HENRY_WALK3_REVERSE             492
#define HENRY_WALK2_REVERSE             493
#define HENRY_WALK1_REVERSE             494
#define BITMAP_HEALTHBAR2               495
#define RED                             496
#define IDB_BITMAP43                    497
#define FIRZEN_S                        497
#define FREEZE_S                        498
#define HENRY_S                         499
#define PLAYER0_S                       500
#define HENRY_ATTACK1                   501
#define HENRY_ATTACK3                   502
#define HENRY_ATTACK4                   503
#define HENRY_ATTACK4_REVERSE           504
#define HENRY_ATTACK3_REVERSE           505
#define HENRY_ATTACK1_REVERSE           506
#define HENRY_JUMP1                     507
#define HENRY_JUMP2                     508
#define HENRY_JUMP3                     509
#define HENRY_JUMP3_REVERSE             510
#define HENRY_JUMP2_REVERSE             511
#define HENRY_JUMP1_REVERSE             512
#define HENRY_RUN1                      513
#define HENRY_RUN2                      514
#define HENRY_RUN3                      515
#define HENRY_RUN3_REVERSE              516
#define HENRY_RUN2_REVERSE              517
#define HENRY_RUN1_REVERSE              518
#define HENRY_ATTACK2                   519
#define HENRY_ATTACK2_REVERSE           520
#define HENRY_KNOCK1                    521
#define HENRY_KNOCK2                    522
#define HENRY_KNOCK3                    523
#define HENRY_KNOCK4                    524
#define HENRY_KNOCK5                    525
#define HENRY_KNOCK5_REVERSE            526
#define HENRY_KNOCK4_REVERSE            527
#define HENRY_KNOCK3_REVERSE            528
#define HENRY_KNOCK2_REVERSE            529
#define HENRY_KNOCK1_REVERSE            530
#define HENRY_KNOCKBACK1                531
#define HENRY_KNOCKBACK2                532
#define HENRY_KNOCKBACK3                533
#define HENRY_KNOCKBACK4                534
#define HENRY_KNOCKBACK5                535
#define HENRY_KNOCKBACK5_REVERSE        536
#define HENRY_KNOCKBACK4_REVERSE        537
#define HENRY_KNOCKBACK3_REVERSE        538
#define HENRY_KNOCKBACK2_REVERSE        539
#define HENRY_KNOCKBACK1_REVERSE        540
#define HENRY_GETUP1                    541
#define HENRY_GETUP2                    542
#define HENRY_GETUP2_REVERSE            543
#define HENRY_GETUP1_REVERSE            544
#define HENRY_GETUPBACK1                545
#define HENRY_GETUPBACK1_REVERSE        546
#define BITMAP_FOREST_M2                547
#define BITMAP_FOREST_M3                548
#define BITMAP_FOREST_M4                549
#define BITMAP_FOREST_M5                550
#define BITMAP_FOREST_T1                551
#define BITMAP_FOREST_L1                552
#define BITMAP_FOREST_L2                553
#define BITMAP_FOREST_L3                554
#define BITMAP_FOREST_L4                555
#define BITMAP_FOREST_S1                556
#define BITMAP_FOREST_B                 557
#define IDB_BITMAP33                    558
#define IDB_BITMAP34                    559
#define IDB_BITMAP35                    560
#define BITMAP_GREEN                    561
#define IDB_BITMAP36                    562
#define BITMAP_FOREST_Mex               563
#define IDB_BITMAP37                    564
#define IDB_BITMAP38                    565
#define IDB_BITMAP39                    566
#define IDB_BITMAP40                    567
#define IDC_README                      568
#define IDB_BITMAP14                    569
#define IDB_BITMAP15                    570
#define IDB_BITMAP16                    571
#define IDB_BITMAP17                    572
#define IDB_BITMAP18                    573
#define IDB_BITMAP19                    574
#define IDB_BITMAP20                    575
#define IDB_BITMAP21                    576
#define IDB_BITMAP22                    577
#define IDB_BITMAP23                    578
#define IDB_BITMAP24                    579
#define IDB_BITMAP25                    580
#define IDB_BITMAP26                    581
#define IDB_BITMAP27                    582
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775
#define BITMAP_COUNTDOWN_BACK           57664

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        501
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
